import type { Project } from "@repo/types";

// Shared project data — no "use client" directive so it can be imported
// by both the Server Component (generateStaticParams) and Client Component (rendering)

export interface ProjectData {
  slug: string;
  title: string;
  badge: string;
  location: string;
  startingPrice: string;
  appreciation: string;
  rentalYield: string;
  horizon: string;
  overview: string;
  heroImage: string;
  galleryMain: string;
  gallerySub1: string;
  gallerySub2: string;
  developerName: string;
  developerDesc: string;
}

export const PROJECTS_DATA: Record<string, ProjectData> = {
  "vedha-bhoomi": {
    slug: "vedha-bhoomi",
    title: "Vedha Bhoomi — Luxury Farmland Plots",
    badge: "FLAGSHIP PROJECT",
    location: "Near Lepakshi, North Bengaluru",
    startingPrice: "₹22 Lakhs",
    appreciation: "18% p.a.",
    rentalYield: "5.5%",
    horizon: "3-7 Yrs",
    overview:
      "Vedha Bhoomi is a premium gated farmland community by Vedha Sree Parivar LLP, nestled in the serene landscapes near Lepakshi — just 90 km from Kempegowda International Airport, North Bengaluru.\n\nSpread across 40 acres (with Phase 1 across 18 acres) and divided into 63 luxury farm plots, each plot comes with up to 400 plants and fruit-bearing trees, comprehensive drip irrigation, and access to a world-class clubhouse. With clear legal title deeds, Vedha Bhoomi offers a rare combination of weekend retreat living and strong long-term land appreciation along the Bengaluru–Vijayawada Expressway growth corridor.",
    heroImage: "/vedhabhoomi/vedhabhoomi1.jpg",
    galleryMain: "/vedhabhoomi/vedhabhoomi2.jpeg",
    gallerySub1: "/vedhabhoomi/vedhabhoomi3.jpeg",
    gallerySub2: "/vedhabhoomi/vedhabhoomi4.jpeg",
    developerName: "Vedha Sree Parivar LLP",
    developerDesc:
      "Vedha Sree Parivar LLP is a trusted real estate developer specializing in premium managed farmland communities across South India, with a strong focus on eco-friendly infrastructure, legal transparency, and long-term investor returns.",
  },

  "marina-crown": {
    slug: "marina-crown",
    title: "Devanahalli Aerotropolis Layout",
    badge: "EXCLUSIVE PLOT",
    location: "Devanahalli, Bengaluru",
    startingPrice: "₹1.25 Cr",
    appreciation: "14.5% p.a.",
    rentalYield: "8.5%",
    horizon: "3-5 Yrs",
    overview:
      "Devanahalli Aerotropolis Layout represents the premier land investment opportunity in North Bengaluru's fastest-growing growth corridor. Located minutes from Kempegowda International Airport and the 12,000-acre ITIR SEZ, this BIAPPA & RERA-approved layout features wide asphalt roads, underground cabling, and landscaped avenues.\n\nIdeal for investors seeking high annual land appreciation driven by major infrastructure projects including the Namma Metro Blue Line extension and Satellite Town Ring Road (STRR).",
    heroImage: "/property-1.jpg",
    galleryMain: "/gallery-interior.jpg",
    gallerySub1: "/property-1.jpg",
    gallerySub2: "/gallery-lounge.jpg",
    developerName: "Prestige Group",
    developerDesc:
      "With over 30 years of development excellence in Bengaluru, Prestige Group is renowned for landmark plotted communities, luxury towers, and high-yield asset delivery.",
  },
  "mayfair-exchange": {
    slug: "mayfair-exchange",
    title: "Sarjapur Tech Corridor",
    badge: "HIGH GROWTH",
    location: "Sarjapur Road, Bengaluru",
    startingPrice: "₹85 Lakhs",
    appreciation: "12.8% p.a.",
    rentalYield: "7.2%",
    horizon: "4-6 Yrs",
    overview:
      "Sarjapur Tech Corridor is a premier residential & commercial plotted development strategically positioned between Outer Ring Road, Electronic City, and Whitefield tech hubs. Featuring BDA-approved layout specifications, overhead solar lighting, and 24/7 security, it delivers sustained capital growth and high tenant demand.",
    heroImage: "/property-2.jpg",
    galleryMain: "/gallery-lounge.jpg",
    gallerySub1: "/property-2.jpg",
    gallerySub2: "/gallery-interior.jpg",
    developerName: "Sobha Developers",
    developerDesc:
      "A trusted legacy of precision engineering, backward integration, and top-tier residential layouts across South India.",
  },
  "palm-estate": {
    slug: "palm-estate",
    title: "The Imperial Palm Villas",
    badge: "LUXURY VILLA",
    location: "Yelahanka, Bengaluru",
    startingPrice: "₹4.5 Cr",
    appreciation: "10.2% p.a.",
    rentalYield: "6.5%",
    horizon: "5-8 Yrs",
    overview:
      "An ultra-exclusive gated villa estate offering private plunge pools, lush clubhouse amenities, and bespoke architectural finishes tailored for discerning investors seeking long-term capital preservation in North Bengaluru's serene micro-market.",
    heroImage: "/property-3.jpg",
    galleryMain: "/property-3.jpg",
    gallerySub1: "/gallery-interior.jpg",
    gallerySub2: "/gallery-lounge.jpg",
    developerName: "Brigade Group",
    developerDesc:
      "Award-winning real estate developer behind iconic residential and commercial projects across Bengaluru.",
  },
  "whitefield-heights": {
    slug: "whitefield-heights",
    title: "Whitefield IT Heights",
    badge: "HIGH YIELD",
    location: "Whitefield, Bengaluru",
    startingPrice: "₹1.8 Cr",
    appreciation: "9.5% p.a.",
    rentalYield: "5.8%",
    horizon: "3-5 Yrs",
    overview:
      "Modern luxury residences located in the heart of Whitefield's IT corridor, adjacent to major tech parks, Purple Line Metro stations, and international schools.",
    heroImage: "/property-1.jpg",
    galleryMain: "/gallery-interior.jpg",
    gallerySub1: "/property-1.jpg",
    gallerySub2: "/gallery-lounge.jpg",
    developerName: "Godrej Properties",
    developerDesc:
      "Pioneering sustainable and design-led real estate developments across India.",
  },
  "greenwood-estates": {
    slug: "greenwood-estates",
    title: "Greenwood Managed Farm Plots",
    badge: "ECO INVESTMENT",
    location: "Kanakapura Road, Bengaluru",
    startingPrice: "₹65 Lakhs",
    appreciation: "13.8% p.a.",
    rentalYield: "4.5%",
    horizon: "4-7 Yrs",
    overview:
      "Scenic managed farmland plots equipped with drip irrigation, fruit orchards, and resort amenities along Kanakapura Road, offering natural retreat living alongside strong land appreciation.",
    heroImage: "/property-2.jpg",
    galleryMain: "/gallery-lounge.jpg",
    gallerySub1: "/property-2.jpg",
    gallerySub2: "/gallery-interior.jpg",
    developerName: "1ASET Managed Land",
    developerDesc:
      "Specialized in high-yield agricultural to non-agricultural land asset curation and turnkey layout management.",
  },
};

export const FALLBACK_PROJECTS: Project[] = [
  {
    id: "vedha-bhoomi",
    slug: "vedha-bhoomi",
    title: "Vedha Bhoomi — Luxury Farmland Plots",
    category: "Farm Plots",
    shortDescription:
      "40-acre gated farmland community near Lepakshi, North Bengaluru. 63 luxury farm plots with drip irrigation, fruit orchards, and world-class clubhouse retreat.",
    fullDescription:
      "Vedha Bhoomi is a premier gated farmland community by Vedha Sree Parivar LLP, nestled in the serene landscapes near Lepakshi — just 90 km from Kempegowda International Airport, North Bengaluru.\n\nSpread across 40 acres (with Phase 1 across 18 acres) and divided into 63 luxury farm plots, each plot comes with up to 400 plants and fruit-bearing trees, comprehensive drip irrigation, and access to a world-class clubhouse. With clear legal title deeds, Vedha Bhoomi offers a rare combination of weekend retreat living and strong long-term land appreciation along the Bengaluru–Vijayawada Expressway growth corridor.",
    badge: "FLAGSHIP PROJECT",
    status: "Clear Title",
    location: "Near Lepakshi, North Bengaluru",
    city: "Bengaluru",
    priceDisplay: "₹22 Lakhs",
    priceVal: 2200000,
    pricePerSqft: 250,
    minInvestment: 2200000,
    expectedRoi: "18% p.a.",
    roiVal: 18,
    expectedAppreciation: "18% p.a.",
    rentalYield: "6.5%",
    horizon: "3-5 Yrs",
    areaSqft: "10,600 sqft",
    totalAcres: "40 Acres",
    totalPlots: 63,
    heroImage: "/vedhabhoomi/vedhabhoomi1.jpg",
    featuredImage: "/vedhabhoomi/vedhabhoomi1.jpg",
    galleryImages: [
      { src: "/vedhabhoomi/vedhabhoomi2.jpeg", title: "Internal Asphalt Roads & Tree Lines" },
      { src: "/vedhabhoomi/vedhabhoomi3.jpeg", title: "Plot Boundary Demarcation" },
      { src: "/vedhabhoomi/vedhabhoomi4.jpeg", title: "Panoramic Farmland Vista" },
    ],
    videoTourUrl: "/vedhabhoomi/vedhabhoomi7.mp4",
    developerName: "Vedha Sree Parivar LLP",
    developerDesc:
      "A trusted real estate developer specializing in premium gated communities and farmland assets across South India.",
    amenities: [
      { label: "Drip Irrigation System" },
      { label: "24/7 CCTV Security & Gated Entry" },
      { label: "Internal Asphalt Roads" },
      { label: "Borewell & Water Supply" },
      { label: "Clubhouse Retreat" },
    ],
    highlights: [
      { value: "40 Acres", label: "Total Area" },
      { value: "63", label: "Total Units / Plots" },
      { value: "18% p.a.", label: "Expected ROI" },
      { value: "3-5 Yrs", label: "Investment Horizon" },
    ],
    legalChecks: [
      "100% Clear Title & Ownership",
      "Clear Patta & Legal Title Deed",
      "Agricultural Farmland",
      "Water Test Reports Available",
      "Soil Test Reports Available",
      "Registered Sale Deed",
    ],
    featured: true,
    isFlagship: true,
    published: true,
  },
  {
    id: "marina-crown",
    slug: "marina-crown",
    title: "Devanahalli Aerotropolis Layout",
    category: "Open Plots",
    shortDescription:
      "BIAPPA & RERA-approved plotted development minutes from Kempegowda International Airport and 12,000-acre ITIR SEZ.",
    fullDescription:
      "Devanahalli Aerotropolis Layout represents the premier land investment opportunity in North Bengaluru fastest-growing growth corridor. Located minutes from Kempegowda International Airport and the 12,000-acre ITIR SEZ, this layout features wide asphalt roads, underground cabling, and landscaped avenues.\n\nIdeal for investors seeking high annual land appreciation driven by major infrastructure projects including the Namma Metro Blue Line extension and Satellite Town Ring Road (STRR).",
    badge: "EXCLUSIVE PLOT",
    status: "Active",
    location: "Devanahalli, Bengaluru",
    city: "Bengaluru",
    priceDisplay: "₹1.25 Cr",
    priceVal: 12500000,
    pricePerSqft: 5200,
    minInvestment: 12500000,
    expectedRoi: "14.5% p.a.",
    roiVal: 14.5,
    expectedAppreciation: "14.5% p.a.",
    rentalYield: "8.5%",
    horizon: "3-5 Yrs",
    areaSqft: "2,400 sqft",
    totalAcres: "25 Acres",
    totalPlots: 120,
    heroImage: "/property-1.jpg",
    featuredImage: "/property-1.jpg",
    galleryImages: [
      { src: "/gallery-interior.jpg", title: "Layout Landscaping" },
      { src: "/property-1.jpg", title: "Avenue Roads" },
      { src: "/gallery-lounge.jpg", title: "Clubhouse Amenities" },
    ],
    developerName: "Prestige Group",
    developerDesc:
      "With over 30 years of development excellence in Bengaluru, Prestige Group is renowned for landmark plotted communities, luxury towers, and high-yield asset delivery.",
    amenities: [
      { label: "Underground Cabling & Drainage" },
      { label: "Wide Asphalt Roads" },
      { label: "24/7 Security" },
      { label: "Clubhouse & Sports Courts" },
    ],
    highlights: [
      { value: "25 Acres", label: "Total Area" },
      { value: "120", label: "Total Units / Plots" },
      { value: "14.5% p.a.", label: "Expected ROI" },
      { value: "3-5 Yrs", label: "Investment Horizon" },
    ],
    legalChecks: ["BIAPPA Approved", "RERA Registered", "Bank Loan Approved"],
    featured: true,
    isFlagship: false,
    published: true,
  },
  {
    id: "mayfair-exchange",
    slug: "mayfair-exchange",
    title: "Sarjapur Tech Corridor",
    category: "Open Plots",
    shortDescription:
      "Strategically positioned between Outer Ring Road, Electronic City, and Whitefield tech hubs.",
    fullDescription:
      "Sarjapur Tech Corridor is a premier residential & commercial plotted development strategically positioned between Outer Ring Road, Electronic City, and Whitefield tech hubs. Featuring BDA-approved layout specifications, overhead solar lighting, and 24/7 security, it delivers sustained capital growth and high tenant demand.",
    badge: "HIGH GROWTH",
    status: "Active",
    location: "Sarjapur Road, Bengaluru",
    city: "Bengaluru",
    priceDisplay: "₹85 Lakhs",
    priceVal: 8500000,
    pricePerSqft: 5666,
    minInvestment: 8500000,
    expectedRoi: "12.8% p.a.",
    roiVal: 12.8,
    expectedAppreciation: "12.8% p.a.",
    rentalYield: "7.2%",
    horizon: "4-6 Yrs",
    areaSqft: "1,500 sqft",
    totalAcres: "15 Acres",
    totalPlots: 85,
    heroImage: "/property-2.jpg",
    featuredImage: "/property-2.jpg",
    galleryImages: [
      { src: "/gallery-lounge.jpg", title: "Clubhouse" },
      { src: "/property-2.jpg", title: "Avenue View" },
      { src: "/gallery-interior.jpg", title: "Common Amenities" },
    ],
    developerName: "Sobha Developers",
    developerDesc:
      "A trusted legacy of precision engineering, backward integration, and top-tier residential layouts across South India.",
    amenities: [
      { label: "BDA Layout Specification" },
      { label: "Solar Street Lighting" },
      { label: "24/7 Manned Security" },
      { label: "Rainwater Harvesting" },
    ],
    highlights: [
      { value: "15 Acres", label: "Total Area" },
      { value: "85", label: "Total Units / Plots" },
      { value: "12.8% p.a.", label: "Expected ROI" },
      { value: "4-6 Yrs", label: "Investment Horizon" },
    ],
    legalChecks: ["BDA Approved", "RERA Registered", "Clear Title"],
    featured: true,
    isFlagship: false,
    published: true,
  },
  {
    id: "palm-estate",
    slug: "palm-estate",
    title: "The Imperial Palm Villas",
    category: "Villas",
    shortDescription:
      "Ultra-exclusive gated villa estate offering private plunge pools and lush clubhouse amenities.",
    fullDescription:
      "An ultra-exclusive gated villa estate offering private plunge pools, lush clubhouse amenities, and bespoke architectural finishes tailored for discerning investors seeking long-term capital preservation in North Bengaluru serene micro-market.",
    badge: "LUXURY VILLA",
    status: "Active",
    location: "Yelahanka, Bengaluru",
    city: "Bengaluru",
    priceDisplay: "₹4.5 Cr",
    priceVal: 45000000,
    minInvestment: 45000000,
    expectedRoi: "10.2% p.a.",
    roiVal: 10.2,
    expectedAppreciation: "10.2% p.a.",
    rentalYield: "6.5%",
    horizon: "5-8 Yrs",
    areaSqft: "4,800 sqft",
    totalAcres: "12 Acres",
    totalPlots: 32,
    heroImage: "/property-3.jpg",
    featuredImage: "/property-3.jpg",
    galleryImages: [
      { src: "/property-3.jpg", title: "Villa Exterior" },
      { src: "/gallery-interior.jpg", title: "Living Spaces" },
      { src: "/gallery-lounge.jpg", title: "Clubhouse Lounge" },
    ],
    developerName: "Brigade Group",
    developerDesc:
      "Award-winning real estate developer behind iconic residential and commercial projects across Bengaluru.",
    amenities: [
      { label: "Private Plunge Pools" },
      { label: "Tennis & Badminton Courts" },
      { label: "24/7 Concierge" },
    ],
    highlights: [
      { value: "12 Acres", label: "Total Area" },
      { value: "32", label: "Total Units / Plots" },
      { value: "10.2% p.a.", label: "Expected ROI" },
      { value: "5-8 Yrs", label: "Investment Horizon" },
    ],
    legalChecks: ["A-Khata Title", "OC Received", "Bank Approved"],
    featured: true,
    isFlagship: false,
    published: true,
  },
  {
    id: "whitefield-heights",
    slug: "whitefield-heights",
    title: "Whitefield IT Heights",
    category: "Apartments",
    shortDescription:
      "Modern luxury residences located in the heart of Whitefield IT corridor.",
    fullDescription:
      "Modern luxury residences located in the heart of Whitefield IT corridor, adjacent to major tech parks, Purple Line Metro stations, and international schools.",
    badge: "HIGH YIELD",
    status: "Under Review",
    location: "Whitefield, Bengaluru",
    city: "Bengaluru",
    priceDisplay: "₹1.8 Cr",
    priceVal: 18000000,
    minInvestment: 18000000,
    expectedRoi: "9.5% p.a.",
    roiVal: 9.5,
    expectedAppreciation: "9.5% p.a.",
    rentalYield: "5.8%",
    horizon: "3-5 Yrs",
    areaSqft: "2,100 sqft",
    totalAcres: "8 Acres",
    totalPlots: 180,
    heroImage: "/property-1.jpg",
    featuredImage: "/property-1.jpg",
    galleryImages: [
      { src: "/gallery-interior.jpg", title: "Interiors" },
      { src: "/property-1.jpg", title: "Elevation" },
    ],
    developerName: "Godrej Properties",
    developerDesc: "Pioneering sustainable and design-led real estate developments across India.",
    amenities: [
      { label: "Infinity Pool" },
      { label: "Co-working Space" },
      { label: "EV Charging Stations" },
    ],
    highlights: [
      { value: "8 Acres", label: "Total Area" },
      { value: "180", label: "Total Units" },
      { value: "9.5% p.a.", label: "Expected ROI" },
    ],
    legalChecks: ["RERA Approved", "B-DA NOC", "Clear Title"],
    featured: false,
    isFlagship: false,
    published: true,
  },
  {
    id: "greenwood-estates",
    slug: "greenwood-estates",
    title: "Greenwood Managed Farm Plots",
    category: "Farm Plots",
    shortDescription:
      "Scenic managed farmland plots equipped with drip irrigation and resort amenities along Kanakapura Road.",
    fullDescription:
      "Scenic managed farmland plots equipped with drip irrigation, fruit orchards, and resort amenities along Kanakapura Road, offering natural retreat living alongside strong land appreciation.",
    badge: "ECO INVESTMENT",
    status: "Clear Title",
    location: "Kanakapura Road, Bengaluru",
    city: "Bengaluru",
    priceDisplay: "₹65 Lakhs",
    priceVal: 6500000,
    minInvestment: 6500000,
    expectedRoi: "13.8% p.a.",
    roiVal: 13.8,
    expectedAppreciation: "13.8% p.a.",
    rentalYield: "4.5%",
    horizon: "4-7 Yrs",
    areaSqft: "6,000 sqft",
    totalAcres: "30 Acres",
    totalPlots: 45,
    heroImage: "/property-2.jpg",
    featuredImage: "/property-2.jpg",
    galleryImages: [
      { src: "/property-2.jpg", title: "Farm Panorama" },
      { src: "/gallery-lounge.jpg", title: "Clubhouse" },
    ],
    developerName: "1ASET Managed Land",
    developerDesc:
      "Specialized in high-yield agricultural to non-agricultural land asset curation and turnkey layout management.",
    amenities: [
      { label: "Organic Farming Management" },
      { label: "Drip Irrigation" },
      { label: "Eco Clubhouse" },
    ],
    highlights: [
      { value: "30 Acres", label: "Total Area" },
      { value: "45", label: "Total Units / Plots" },
      { value: "13.8% p.a.", label: "Expected ROI" },
      { value: "4-7 Yrs", label: "Investment Horizon" },
    ],
    legalChecks: ["Agricultural Title", "Clear Patta", "Survey Demarcation"],
    featured: false,
    isFlagship: false,
    published: true,
  },
  {
    id: "north-bengaluru-gate",
    slug: "north-bengaluru-gate",
    title: "North Bengaluru Gateway Layout",
    category: "Open Plots",
    shortDescription:
      "Prime plotted land in Devanahalli with direct access to Satellite Town Ring Road (STRR).",
    fullDescription:
      "Strategically situated in Devanahalli with instant connectivity to the upcoming Satellite Town Ring Road and Airport Express line. High-potential capital appreciation corridor.",
    badge: "PRIME LAND",
    status: "Active",
    location: "Devanahalli, Bengaluru",
    city: "Bengaluru",
    priceDisplay: "₹2.4 Cr",
    priceVal: 24000000,
    minInvestment: 24000000,
    expectedRoi: "15.2% p.a.",
    roiVal: 15.2,
    expectedAppreciation: "15.2% p.a.",
    rentalYield: "6.0%",
    horizon: "3-5 Yrs",
    areaSqft: "3,200 sqft",
    totalAcres: "18 Acres",
    totalPlots: 75,
    heroImage: "/property-3.jpg",
    featuredImage: "/property-3.jpg",
    galleryImages: [
      { src: "/property-3.jpg", title: "Gateway Approach" },
      { src: "/gallery-interior.jpg", title: "Park View" },
    ],
    developerName: "Prestige Group",
    developerDesc: "Landmark plotted developer across North Bengaluru corridor.",
    amenities: [
      { label: "Underground Infrastructure" },
      { label: "Landscaped Central Park" },
      { label: "24/7 Security" },
    ],
    highlights: [
      { value: "18 Acres", label: "Total Area" },
      { value: "75", label: "Total Units / Plots" },
      { value: "15.2% p.a.", label: "Expected ROI" },
      { value: "3-5 Yrs", label: "Investment Horizon" },
    ],
    legalChecks: ["BIAPPA Approved", "Clear Title", "RERA Registered"],
    featured: true,
    isFlagship: false,
    published: true,
  },
];

export function getFallbackProject(slug: string): Project | undefined {
  return FALLBACK_PROJECTS.find((p) => p.slug === slug);
}

